### ISSUE TITLE
[feat] 족보 이미지 Entity 추가

### ISSUE THREAD

**Issue by PicturePark1101** [Team-Hankki/hankki-server#15]
## Issue 📌

- 족보 이미지 Entity 추가
- ERD cloud에 이렇게 추가해두었습니다. 
- 경우에 따라 이미지가 바뀌어 하므로 연관관계 설정은 안했습니다
- favorite의 favorite_image_url 필드는 없애도 될 것 같습니다

<img width="396" alt="스크린샷 2024-07-05 오후 7 27 27" src="https://github.com/Team-Hankki/hankki-server/assets/109809242/01752955-e053-49f2-9484-a7ecd2dd76bd">

## Todo ✔️
- [ ] 족보 이미지 Entity 추가
- [ ] favorite의 favorite_image_url 필드제거

**Comment by Parkjyun** [comment]
혹시 족보 이미지 테이블을 따로 관리하는 경우가 있을까요?

**Comment by PicturePark1101** [comment]
S3에서 생성된 URL자체를 Enum으로 관리하자고 하시는 것 맞으실까요?? 저도 로직상 이 방법을 사용하면 더 간단해져서 좋긴합니다 
프론트에서 지정해준 이미지가 변할 일이 별로 없으니 Enum으로 관리하는게 맞을 것 같네요 테이블 삭제하고 개발 들어갈 때 enum 추가하도록 하겠습니다!
